using System.IO;
using Game.Client.UI.Standalone;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;

namespace Game.Client.Editor
{
    /// <summary>
    /// EDITOR-ONLY one-shot authoring utility. It creates an ordinary editable prefab asset.
    /// No part of the runtime UI hierarchy is generated by gameplay code.
    /// </summary>
    public static class StandaloneClientUIAuthoring
    {
        private const string Folder = "Assets/Game/Client/UI/Standalone/Prefabs";
        private const string PrefabPath = Folder + "/StandaloneClientUI.prefab";

        private static readonly Color Background = new Color32(20, 22, 28, 235);
        private static readonly Color Panel = new Color32(34, 37, 45, 245);
        private static readonly Color Panel2 = new Color32(45, 49, 59, 245);
        private static readonly Color Accent = new Color32(66, 112, 170, 255);
        private static readonly Color Border = new Color32(85, 91, 105, 255);
        private static readonly Color TextPrimary = new Color32(235, 238, 242, 255);
        private static readonly Color TextMuted = new Color32(170, 178, 190, 255);

        [MenuItem("MMO Tools/UI/Standalone UI/Create Foundation V1")]
        public static void CreateFoundation()
        {
            EnsureFolders();
            Font font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf") ??
                        Resources.GetBuiltinResource<Font>("Arial.ttf");

            GameObject root = new GameObject("StandaloneClientUI", typeof(RectTransform), typeof(Canvas), typeof(CanvasScaler), typeof(GraphicRaycaster), typeof(StandaloneClientUIRoot));
            RectTransform rootRect = root.GetComponent<RectTransform>();
            Stretch(rootRect);

            Canvas canvas = root.GetComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;
            canvas.sortingOrder = 50;

            CanvasScaler scaler = root.GetComponent<CanvasScaler>();
            scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
            scaler.referenceResolution = new Vector2(1920f, 1080f);
            scaler.screenMatchMode = CanvasScaler.ScreenMatchMode.MatchWidthOrHeight;
            scaler.matchWidthOrHeight = 0.5f;

            GameObject hudLayer = Node("HUD", root.transform);
            Stretch(hudLayer.GetComponent<RectTransform>());
            GameObject windowLayer = Node("Windows", root.transform);
            Stretch(windowLayer.GetComponent<RectTransform>());
            GameObject popupLayer = Node("Popups", root.transform);
            Stretch(popupLayer.GetComponent<RectTransform>());
            GameObject overlayLayer = Node("Overlays", root.transform);
            Stretch(overlayLayer.GetComponent<RectTransform>());

            // Authored HUD placeholders: intentionally simple and easy to dress.
            CreateHudFrame(hudLayer.transform, font, "PlayerStatus", new Vector2(20, -20), new Vector2(320, 92), TextAnchor.UpperLeft, "Character\nHealth / Resource");
            CreateHudFrame(hudLayer.transform, font, "TargetStatus", new Vector2(-20, -20), new Vector2(320, 92), TextAnchor.UpperRight, "Target\nHealth / Status", anchorRight: true);
            CreateActionBar(hudLayer.transform, font);
            CreateChatPlaceholder(hudLayer.transform, font);

            StandaloneHudTooltipPanel tooltip = CreateTooltip(hudLayer.transform, font);
            StandaloneCharacterInventoryWindow characterInventory = CreateCharacterInventory(windowLayer.transform, font, tooltip);

            StandaloneClientUIRoot controller = root.GetComponent<StandaloneClientUIRoot>();
            controller.ConfigureForEditor(characterInventory, tooltip);

            GameObject prefab = PrefabUtility.SaveAsPrefabAsset(root, PrefabPath);
            Object.DestroyImmediate(root);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Selection.activeObject = prefab;
            EditorGUIUtility.PingObject(prefab);
            Debug.Log("[StandaloneUI] Authored prefab created: " + PrefabPath + ". Runtime does not build this hierarchy.");
        }

        private static StandaloneCharacterInventoryWindow CreateCharacterInventory(Transform parent, Font font, StandaloneHudTooltipPanel tooltip)
        {
            GameObject window = PanelObject("CharacterInventory", parent, Background);
            RectTransform wr = window.GetComponent<RectTransform>();
            wr.anchorMin = wr.anchorMax = new Vector2(0.5f, 0.5f);
            wr.pivot = new Vector2(0.5f, 0.5f);
            wr.sizeDelta = new Vector2(1180f, 720f);
            wr.anchoredPosition = Vector2.zero;

            StandaloneCharacterInventoryWindow controller = window.AddComponent<StandaloneCharacterInventoryWindow>();

            GameObject header = PanelObject("Header", window.transform, Panel2);
            SetRect(header.GetComponent<RectTransform>(), new Vector2(0, 1), new Vector2(1, 1), new Vector2(0, 1), new Vector2(0, 0), new Vector2(0, 56));
            Text title = TextObject("Title", header.transform, font, 22, TextPrimary, TextAnchor.MiddleLeft, "CHARACTER / INVENTORY");
            SetOffsets(title.rectTransform, 18, 70, 0, 0);
            Button close = ButtonObject("CloseButton", header.transform, font, "X", new Vector2(48, 40));
            RectTransform closeRect = close.GetComponent<RectTransform>();
            closeRect.anchorMin = closeRect.anchorMax = new Vector2(1, 0.5f);
            closeRect.pivot = new Vector2(1, 0.5f);
            closeRect.anchoredPosition = new Vector2(-8, 0);

            GameObject left = PanelObject("CharacterPanel", window.transform, Panel);
            RectTransform lr = left.GetComponent<RectTransform>();
            lr.anchorMin = new Vector2(0, 0); lr.anchorMax = new Vector2(0.37f, 1); lr.offsetMin = new Vector2(12, 12); lr.offsetMax = new Vector2(-6, -68);

            Text charName = TextObject("CharacterName", left.transform, font, 24, TextPrimary, TextAnchor.UpperLeft, "Character");
            SetRect(charName.rectTransform, new Vector2(0, 1), new Vector2(1, 1), new Vector2(0, 1), new Vector2(16, -16), new Vector2(-32, 34));
            Text level = TextObject("Level", left.transform, font, 16, TextMuted, TextAnchor.UpperLeft, "Level --");
            SetRect(level.rectTransform, new Vector2(0, 1), new Vector2(1, 1), new Vector2(0, 1), new Vector2(16, -52), new Vector2(-32, 26));
            Text summary = TextObject("Summary", left.transform, font, 14, TextMuted, TextAnchor.UpperLeft, "Inventory not hydrated");
            SetRect(summary.rectTransform, new Vector2(0, 1), new Vector2(1, 1), new Vector2(0, 1), new Vector2(16, -82), new Vector2(-32, 24));

            GameObject paperdoll = PanelObject("PaperdollArea", left.transform, new Color32(26, 28, 34, 255));
            RectTransform pr = paperdoll.GetComponent<RectTransform>();
            pr.anchorMin = new Vector2(0, 0.53f); pr.anchorMax = new Vector2(1, 0.82f); pr.offsetMin = new Vector2(16, 0); pr.offsetMax = new Vector2(-16, 0);
            Text paperdollLabel = TextObject("Label", paperdoll.transform, font, 14, TextMuted, TextAnchor.MiddleCenter, "Character preview / paperdoll\n(dress this area later)");
            Stretch(paperdollLabel.rectTransform);

            Text equipmentHeading = TextObject("EquipmentHeading", left.transform, font, 16, TextPrimary, TextAnchor.MiddleLeft, "EQUIPMENT");
            SetRect(equipmentHeading.rectTransform, new Vector2(0, 0.49f), new Vector2(1, 0.49f), new Vector2(0, 0.5f), new Vector2(16, 0), new Vector2(-32, 30));

            GameObject equipmentScrollGo = ScrollArea("EquipmentScroll", left.transform, out ScrollRect equipmentScroll, out RectTransform equipmentContent);
            RectTransform esr = equipmentScrollGo.GetComponent<RectTransform>();
            esr.anchorMin = new Vector2(0, 0); esr.anchorMax = new Vector2(1, 0.47f); esr.offsetMin = new Vector2(16, 16); esr.offsetMax = new Vector2(-16, 0);
            VerticalLayoutGroup eqLayout = equipmentContent.gameObject.AddComponent<VerticalLayoutGroup>();
            eqLayout.spacing = 6; eqLayout.childControlHeight = false; eqLayout.childControlWidth = true; eqLayout.childForceExpandHeight = false; eqLayout.childForceExpandWidth = true;
            ContentSizeFitter eqFitter = equipmentContent.gameObject.AddComponent<ContentSizeFitter>();
            eqFitter.verticalFit = ContentSizeFitter.FitMode.PreferredSize;
            StandaloneEquipmentSlotView eqTemplate = CreateEquipmentSlotTemplate(equipmentContent, font);
            eqTemplate.gameObject.SetActive(false);

            GameObject right = PanelObject("InventoryPanel", window.transform, Panel);
            RectTransform rr = right.GetComponent<RectTransform>();
            rr.anchorMin = new Vector2(0.37f, 0); rr.anchorMax = new Vector2(1, 1); rr.offsetMin = new Vector2(6, 12); rr.offsetMax = new Vector2(-12, -68);

            Text inventoryHeading = TextObject("InventoryHeading", right.transform, font, 18, TextPrimary, TextAnchor.MiddleLeft, "INVENTORY");
            SetRect(inventoryHeading.rectTransform, new Vector2(0, 1), new Vector2(1, 1), new Vector2(0, 1), new Vector2(16, -14), new Vector2(-32, 34));

            GameObject invScrollGo = ScrollArea("InventoryScroll", right.transform, out ScrollRect inventoryScroll, out RectTransform inventoryContent);
            RectTransform isr = invScrollGo.GetComponent<RectTransform>();
            isr.anchorMin = new Vector2(0, 0); isr.anchorMax = new Vector2(1, 1); isr.offsetMin = new Vector2(16, 70); isr.offsetMax = new Vector2(-16, -58);
            GridLayoutGroup grid = inventoryContent.gameObject.AddComponent<GridLayoutGroup>();
            grid.cellSize = new Vector2(96, 96);
            grid.spacing = new Vector2(8, 8);
            grid.constraint = GridLayoutGroup.Constraint.FixedColumnCount;
            grid.constraintCount = 6;
            grid.startCorner = GridLayoutGroup.Corner.UpperLeft;
            grid.childAlignment = TextAnchor.UpperLeft;
            ContentSizeFitter invFitter = inventoryContent.gameObject.AddComponent<ContentSizeFitter>();
            invFitter.verticalFit = ContentSizeFitter.FitMode.PreferredSize;
            StandaloneInventorySlotView invTemplate = CreateInventorySlotTemplate(inventoryContent, font);
            invTemplate.gameObject.SetActive(false);

            Button previous = ButtonObject("PreviousPageButton", right.transform, font, "<", new Vector2(52, 34));
            RectTransform pbr = previous.GetComponent<RectTransform>();
            pbr.anchorMin = pbr.anchorMax = new Vector2(0, 0); pbr.pivot = new Vector2(0, 0); pbr.anchoredPosition = new Vector2(16, 18);
            Button next = ButtonObject("NextPageButton", right.transform, font, ">", new Vector2(52, 34));
            RectTransform nbr = next.GetComponent<RectTransform>();
            nbr.anchorMin = nbr.anchorMax = new Vector2(0, 0); nbr.pivot = new Vector2(0, 0); nbr.anchoredPosition = new Vector2(76, 18);
            Text page = TextObject("PageText", right.transform, font, 14, TextMuted, TextAnchor.MiddleLeft, "Page 1/1");
            SetRect(page.rectTransform, new Vector2(0, 0), new Vector2(0, 0), new Vector2(0, 0), new Vector2(140, 18), new Vector2(180, 34));

            Text feedback = TextObject("Feedback", right.transform, font, 14, new Color32(230, 193, 107, 255), TextAnchor.MiddleRight, string.Empty);
            SetRect(feedback.rectTransform, new Vector2(0.45f, 0), new Vector2(1, 0), new Vector2(1, 0), new Vector2(0, 18), new Vector2(-16, 34));

            controller.ConfigureForEditor(window, close, charName, level, summary, feedback, inventoryContent, invTemplate, previous, next, page, equipmentContent, eqTemplate, tooltip);
            window.SetActive(false);
            return controller;
        }

        private static StandaloneInventorySlotView CreateInventorySlotTemplate(Transform parent, Font font)
        {
            GameObject go = PanelObject("InventorySlotTemplate", parent, Panel2);
            LayoutElement layout = go.AddComponent<LayoutElement>();
            layout.minWidth = 96; layout.minHeight = 96; layout.preferredWidth = 96; layout.preferredHeight = 96;
            Button button = go.AddComponent<Button>();
            button.targetGraphic = go.GetComponent<Image>();

            GameObject selectionGo = PanelObject("SelectedFrame", go.transform, Accent);
            Stretch(selectionGo.GetComponent<RectTransform>());
            selectionGo.GetComponent<Image>().raycastTarget = false;

            Image icon = ImageObject("ItemIcon", go.transform, Color.white);
            RectTransform ir = icon.rectTransform;
            ir.anchorMin = new Vector2(0.5f, 0.5f); ir.anchorMax = new Vector2(0.5f, 0.5f); ir.pivot = new Vector2(0.5f, 0.5f); ir.sizeDelta = new Vector2(56, 56); ir.anchoredPosition = new Vector2(0, 4);
            icon.raycastTarget = false;

            Text slot = TextObject("SlotNumber", go.transform, font, 11, TextMuted, TextAnchor.UpperLeft, "1");
            SetOffsets(slot.rectTransform, 5, 5, 5, 5);
            Text qty = TextObject("Quantity", go.transform, font, 13, TextPrimary, TextAnchor.LowerRight, string.Empty);
            SetOffsets(qty.rectTransform, 5, 5, 5, 5);

            StandaloneInventorySlotView view = go.AddComponent<StandaloneInventorySlotView>();
            view.ConfigureForEditor(button, icon, slot, qty, selectionGo.GetComponent<Image>());
            return view;
        }

        private static StandaloneEquipmentSlotView CreateEquipmentSlotTemplate(Transform parent, Font font)
        {
            GameObject go = PanelObject("EquipmentSlotTemplate", parent, Panel2);
            LayoutElement layout = go.AddComponent<LayoutElement>();
            layout.minHeight = 58; layout.preferredHeight = 58;
            Button button = go.AddComponent<Button>();
            button.targetGraphic = go.GetComponent<Image>();

            Image icon = ImageObject("ItemIcon", go.transform, Color.white);
            RectTransform ir = icon.rectTransform;
            ir.anchorMin = new Vector2(0, 0.5f); ir.anchorMax = new Vector2(0, 0.5f); ir.pivot = new Vector2(0, 0.5f); ir.sizeDelta = new Vector2(42, 42); ir.anchoredPosition = new Vector2(8, 0);
            icon.raycastTarget = false;

            Text slot = TextObject("SlotName", go.transform, font, 12, TextMuted, TextAnchor.UpperLeft, "Slot");
            SetRect(slot.rectTransform, new Vector2(0, 0), new Vector2(1, 1), new Vector2(0, 1), new Vector2(58, -7), new Vector2(-10, 22));
            Text item = TextObject("ItemName", go.transform, font, 14, TextPrimary, TextAnchor.LowerLeft, "Empty");
            SetRect(item.rectTransform, new Vector2(0, 0), new Vector2(1, 1), new Vector2(0, 0), new Vector2(58, 7), new Vector2(-10, 24));

            StandaloneEquipmentSlotView view = go.AddComponent<StandaloneEquipmentSlotView>();
            view.ConfigureForEditor(button, icon, slot, item);
            return view;
        }

        private static StandaloneHudTooltipPanel CreateTooltip(Transform parent, Font font)
        {
            GameObject root = PanelObject("TooltipPanel", parent, new Color32(17, 18, 22, 248));
            RectTransform rr = root.GetComponent<RectTransform>();
            rr.anchorMin = rr.anchorMax = new Vector2(1, 0.5f);
            rr.pivot = new Vector2(1, 0.5f);
            rr.sizeDelta = new Vector2(330, 210);
            rr.anchoredPosition = new Vector2(-24, 0);
            Outline outline = root.AddComponent<Outline>();
            outline.effectColor = Border;
            outline.effectDistance = new Vector2(1, -1);

            Image icon = ImageObject("Icon", root.transform, Color.white);
            RectTransform ir = icon.rectTransform;
            ir.anchorMin = ir.anchorMax = new Vector2(0, 1); ir.pivot = new Vector2(0, 1); ir.sizeDelta = new Vector2(52, 52); ir.anchoredPosition = new Vector2(14, -14);
            icon.raycastTarget = false;

            Text title = TextObject("Title", root.transform, font, 18, TextPrimary, TextAnchor.UpperLeft, "Tooltip");
            SetRect(title.rectTransform, new Vector2(0, 1), new Vector2(1, 1), new Vector2(0, 1), new Vector2(76, -14), new Vector2(-14, 36));
            Text body = TextObject("Body", root.transform, font, 14, TextMuted, TextAnchor.UpperLeft, string.Empty);
            body.horizontalOverflow = HorizontalWrapMode.Wrap;
            body.verticalOverflow = VerticalWrapMode.Overflow;
            SetRect(body.rectTransform, new Vector2(0, 0), new Vector2(1, 1), new Vector2(0, 0), new Vector2(14, 14), new Vector2(-14, -76));

            root.GetComponent<Image>().raycastTarget = false;
            StandaloneHudTooltipPanel tooltip = root.AddComponent<StandaloneHudTooltipPanel>();
            tooltip.ConfigureForEditor(root, icon, title, body);
            root.SetActive(false);
            return tooltip;
        }

        private static void CreateActionBar(Transform parent, Font font)
        {
            GameObject bar = PanelObject("ActionBar", parent, Background);
            RectTransform br = bar.GetComponent<RectTransform>();
            br.anchorMin = br.anchorMax = new Vector2(0.5f, 0); br.pivot = new Vector2(0.5f, 0); br.sizeDelta = new Vector2(650, 72); br.anchoredPosition = new Vector2(0, 18);
            HorizontalLayoutGroup layout = bar.AddComponent<HorizontalLayoutGroup>();
            layout.padding = new RectOffset(9, 9, 9, 9); layout.spacing = 6; layout.childAlignment = TextAnchor.MiddleCenter; layout.childControlHeight = false; layout.childControlWidth = false;
            for (int i = 1; i <= 10; ++i)
            {
                Button b = ButtonObject("Action" + i, bar.transform, font, i == 10 ? "0" : i.ToString(), new Vector2(54, 54));
                b.interactable = false;
            }
        }

        private static void CreateChatPlaceholder(Transform parent, Font font)
        {
            GameObject chat = PanelObject("Chat", parent, new Color32(18, 20, 25, 215));
            RectTransform cr = chat.GetComponent<RectTransform>();
            cr.anchorMin = cr.anchorMax = new Vector2(0, 0); cr.pivot = new Vector2(0, 0); cr.sizeDelta = new Vector2(470, 210); cr.anchoredPosition = new Vector2(20, 20);
            chat.GetComponent<Image>().raycastTarget = false;
            Text text = TextObject("Placeholder", chat.transform, font, 13, TextMuted, TextAnchor.LowerLeft, "Chat area\n(existing chat transport will bind here in a later pass)");
            SetOffsets(text.rectTransform, 12, 12, 12, 12);
        }

        private static void CreateHudFrame(Transform parent, Font font, string name, Vector2 anchoredPosition, Vector2 size, TextAnchor alignment, string content, bool anchorRight = false)
        {
            GameObject frame = PanelObject(name, parent, new Color32(18, 20, 25, 220));
            RectTransform rect = frame.GetComponent<RectTransform>();
            rect.anchorMin = rect.anchorMax = anchorRight ? new Vector2(1, 1) : new Vector2(0, 1);
            rect.pivot = anchorRight ? new Vector2(1, 1) : new Vector2(0, 1);
            rect.sizeDelta = size;
            rect.anchoredPosition = anchoredPosition;
            frame.GetComponent<Image>().raycastTarget = false;
            Text label = TextObject("Text", frame.transform, font, 14, TextMuted, alignment, content);
            SetOffsets(label.rectTransform, 12, 12, 10, 10);
        }

        private static GameObject ScrollArea(string name, Transform parent, out ScrollRect scroll, out RectTransform content)
        {
            GameObject root = PanelObject(name, parent, new Color32(24, 26, 32, 255));
            scroll = root.AddComponent<ScrollRect>();
            scroll.horizontal = false;
            scroll.vertical = true;
            scroll.scrollSensitivity = 22;

            GameObject viewport = PanelObject("Viewport", root.transform, Color.clear);
            Stretch(viewport.GetComponent<RectTransform>());
            viewport.AddComponent<RectMask2D>();
            scroll.viewport = viewport.GetComponent<RectTransform>();

            GameObject contentGo = Node("Content", viewport.transform);
            content = contentGo.GetComponent<RectTransform>();
            content.anchorMin = new Vector2(0, 1); content.anchorMax = new Vector2(1, 1); content.pivot = new Vector2(0.5f, 1); content.sizeDelta = Vector2.zero; content.anchoredPosition = Vector2.zero;
            scroll.content = content;
            return root;
        }

        private static GameObject Node(string name, Transform parent)
        {
            GameObject go = new GameObject(name, typeof(RectTransform));
            go.transform.SetParent(parent, false);
            return go;
        }

        private static GameObject PanelObject(string name, Transform parent, Color color)
        {
            GameObject go = new GameObject(name, typeof(RectTransform), typeof(CanvasRenderer), typeof(Image));
            go.transform.SetParent(parent, false);
            Image image = go.GetComponent<Image>();
            image.color = color;
            image.raycastTarget = color.a > 0.01f;
            return go;
        }

        private static Image ImageObject(string name, Transform parent, Color color)
        {
            GameObject go = new GameObject(name, typeof(RectTransform), typeof(CanvasRenderer), typeof(Image));
            go.transform.SetParent(parent, false);
            Image image = go.GetComponent<Image>();
            image.color = color;
            return image;
        }

        private static Text TextObject(string name, Transform parent, Font font, int size, Color color, TextAnchor alignment, string value)
        {
            GameObject go = new GameObject(name, typeof(RectTransform), typeof(CanvasRenderer), typeof(Text));
            go.transform.SetParent(parent, false);
            Text text = go.GetComponent<Text>();
            text.font = font;
            text.fontSize = size;
            text.color = color;
            text.alignment = alignment;
            text.text = value;
            text.raycastTarget = false;
            text.horizontalOverflow = HorizontalWrapMode.Wrap;
            text.verticalOverflow = VerticalWrapMode.Truncate;
            return text;
        }

        private static Button ButtonObject(string name, Transform parent, Font font, string label, Vector2 size)
        {
            GameObject go = PanelObject(name, parent, Panel2);
            RectTransform rect = go.GetComponent<RectTransform>();
            rect.sizeDelta = size;
            Button button = go.AddComponent<Button>();
            button.targetGraphic = go.GetComponent<Image>();
            ColorBlock colors = button.colors;
            colors.normalColor = Panel2;
            colors.highlightedColor = Accent;
            colors.pressedColor = new Color32(52, 85, 126, 255);
            colors.selectedColor = Accent;
            colors.disabledColor = new Color32(45, 49, 59, 120);
            button.colors = colors;
            Text text = TextObject("Text", go.transform, font, 16, TextPrimary, TextAnchor.MiddleCenter, label);
            Stretch(text.rectTransform);
            return button;
        }

        private static void Stretch(RectTransform rect)
        {
            rect.anchorMin = Vector2.zero;
            rect.anchorMax = Vector2.one;
            rect.offsetMin = Vector2.zero;
            rect.offsetMax = Vector2.zero;
        }

        private static void SetOffsets(RectTransform rect, float left, float right, float bottom, float top)
        {
            rect.anchorMin = Vector2.zero;
            rect.anchorMax = Vector2.one;
            rect.offsetMin = new Vector2(left, bottom);
            rect.offsetMax = new Vector2(-right, -top);
        }

        private static void SetRect(RectTransform rect, Vector2 anchorMin, Vector2 anchorMax, Vector2 pivot, Vector2 anchoredPosition, Vector2 sizeDelta)
        {
            rect.anchorMin = anchorMin;
            rect.anchorMax = anchorMax;
            rect.pivot = pivot;
            rect.anchoredPosition = anchoredPosition;
            rect.sizeDelta = sizeDelta;
        }

        private static void EnsureFolders()
        {
            string[] parts = Folder.Split('/');
            string current = parts[0];
            for (int i = 1; i < parts.Length; ++i)
            {
                string next = current + "/" + parts[i];
                if (!AssetDatabase.IsValidFolder(next))
                    AssetDatabase.CreateFolder(current, parts[i]);
                current = next;
            }
        }
    }
}
